

version: '3.8'

services:
  my-postgres:
    image: postgres:16
    container_name: db
    environment:
     - POSTGRES_DB=${DATABASE_NAME}
     - POSTGRES_USER=${DATABASE_USER}
     - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
    - '5432:5432'
    volumes:
    - pg_data:/var/lib/postgresql/data

  web:
    #build: .
    image: localhost:5000/django_prueba_test-todo-app:1.0.0
    container_name: django-web-app1
    networks:
      - my-app
    ports:
      - '9000:9000'
    volumes:
      - .:/app
    environment:
      - DJANGO_ENV=${DJANGO_ENV}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    #depends_on:
    #  - my-postgres

volumes:
  pg_data:

networks:
  my-app:
    name: my-django-postgres-network
    external: true